pipeline {
    agent any

    tools {
        // nom exact du Maven configuré dans Jenkins
        maven 'M2_HOME'
    }

    stages {

        stage('Maven Build') {
            steps {
                dir('student-management') {
                    sh 'mvn clean verify'
                }
            }
        }

        stage('MVN SONARQUBE') {
            steps {
                dir('student-management') {
                    sh '''
                      mvn sonar:sonar \
                        -Dsonar.projectKey=student-management \
                        -Dsonar.host.url=http://localhost:9000 \
                        -Dsonar.login=admin \
                        -Dsonar.password=sonar
                    '''
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('student-management') {
                    sh '''
                      echo "Fake Docker build pour l atelier"
                      exit 1
                    '''
                }
            }
        }

        stage('Docker Login') {
            steps {
                dir('student-management') {
                    sh '''
                      echo "Fake Docker login pour l atelier"
                      exit 1
                    '''
                }
            }
        }

        stage('Docker Push') {
            steps {
                dir('student-management') {
                    sh '''
                      echo "Fake Docker push pour l atelier"
                      exit 1
                    '''
                }
            }
        }
    }
}
