pipeline {
    agent any

    tools {
        maven "M3"
        jdk "jdk17"
    }

    environment {
        dockerImage = "gayth/student-management"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Maven Build') {
            steps {
                sh 'mvn -DskipTests clean package'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t ${dockerImage}:latest .'
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([string(credentialsId: "dockerhub-pass", variable: "DOCKER_PASS")]) {
                    sh 'echo $DOCKER_PASS | docker login -u gayth --password-stdin'
                }
            }
        }

        stage('Docker Push') {
            steps {
                sh 'docker push ${dockerImage}:latest'
            }
        }
    }
}
