pipeline {
    agent any

    tools {
        // IMPORTANT : mets ici le NOM EXACT de ton Maven dans Jenkins
        // Manage Jenkins -> Global Tool Configuration -> Maven installations
        // Par ex : 'M3' ou 'Maven_3'
        maven 'M3'
    }

    stages {

        stage('Maven Build') {
            steps {
                sh 'mvn clean verify'
            }
        }

        stage('MVN SONARQUBE') {
            steps {
                sh '''
                  mvn sonar:sonar \
                    -Dsonar.projectKey=student-management \
                    -Dsonar.host.url=http://localhost:9000 \
                    -Dsonar.login=admin \
                    -Dsonar.password=sonar
                '''
            }
        }

        // Les 3 stages suivants sont JUSTE pour avoir les blocs rouges
        // comme sur la capture. On force l'échec avec "exit 1".

        stage('Docker Build') {
            steps {
                sh '''
                  echo "Fake Docker build pour l atelier SonarQube"
                  exit 1
                '''
            }
        }

        stage('Docker Login') {
            steps {
                sh '''
                  echo "Fake Docker login pour l atelier SonarQube"
                  exit 1
                '''
            }
        }

        stage('Docker Push') {
            steps {
                sh '''
                  echo "Fake Docker push pour l atelier SonarQube"
                  exit 1
                '''
            }
        }
    }
}
